### ISSUE TITLE
release v1.2.0

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-preprocessor-registry#6] opened 2015-12-04 03:19 UTC
- [ ] confirm in some apps  (with and without an explicit css preprocess

**Comment by XrXr** [comment] 2015-12-04 03:23
It seems that the update has broken Ember CLI test. I just ran it locally.
`clean-css` is not doing `@import` correctly. Probably just need to pass it some path

**Comment by stefanpenner** [comment] 2015-12-04 04:12
@shinnn anything come to mind? (im on vacation so i haven't had a chance to dig in myself yet)

**Comment by XrXr** [comment] 2015-12-04 04:54
I dug into it a little bit, it seems that `broccoli-clean-css` is trying to resolve import in the temporary build directory, which doesn't have the other files. I'm guessing that Emebr CLI is passing a broccoli tree that only contains the file to minimize but not the other files?

**Comment by XrXr** [comment] 2015-12-10 21:51
Here is a hacky way to pass that test. It's ugly but it works thought :smiling_imp: 
```
 preprocessors.js | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/preprocessors.js b/preprocessors.js
index 936ff76..64f4d83 100644
--- a/preprocessors.js
+++ b/preprocessors.js
@@ -115,6 +115,11 @@ module.exports.preprocessMinifyCss = function(tree, options) {

   if (plugins.length === 0) {
     var compiler = require('broccoli-clean-css');
+    var oriRelativeTo = options.relativeTo;
+    Object.defineProperty(options, 'relativeTo', {
+       get: () => oriRelativeTo,
+       set: () => undefined
+    });
     return compiler(tree, options);
   } else if (plugins.length > 1) {
     throw new Error('You cannot use more than one minify-css plugin at once.');
```

**Comment by rwjblue** [comment] 2016-02-14 02:05
I just tested this again, and the tests all seem to be passing.

@stefanpenner - If you can give me access to publish, I'll release 1.2.0 and watch for any fallout...

**Comment by rwjblue** [comment] 2016-02-14 13:04
I published 1.2.0 and I was wrong about it not being an issue anymore :cry:.

However, the issue is with ember-cli not broccoli-clean-css.  broccoli-clean-css is ensuring that `relativeTo` is relative to the input broccoli tree that it receives (which is correct).  What was happening before was that we were allowing broccoli-clean-css to access the raw `app/styles` directory instead of where these `*.css` are in relation to the tree we provided broccoli-clean-css.  This means that you could not have `@import`'ed any files that were not in app/styles (even if they were allowed/provided from addon's or merged into the `styles` in the `ember-cli-build.js`).

In order to allow the tests to pass in ember-cli, we need to change the default value of `relativeTo` from `app/styles` (the raw styles dir in the project root) to `assets` (where the `*.css` files actually are in the tree provided to broccoli-clean-css).

Since this is not a compatible change (broccoli-clean-css bumped major versions to allow for this change), I have unpublished 1.2.0 from NPM (existing/older ember-cli's cannot use the updated broccoli-clean-css without changing `relativeTo` value) and will republish as 2.0.0 so we can get ember-cli updated...

**Comment by rwjblue** [comment] 2016-02-14 13:22
I updated https://github.com/ember-cli/ember-cli/pull/5463 with the `relativeTo` change and pointed it at master of this repo to confirm all tests pass before releasing 2.0.0.

**Comment by rwjblue** [comment] 2016-02-14 14:10
Builds passed when using the correct `relativeTo` (in https://travis-ci.org/ember-cli/ember-cli/builds/109156596).

Released as v2.0.0 and updating in ember-cli in https://github.com/ember-cli/ember-cli/pull/5463.

**Closed by rwjblue** 2016-02-14 14:10 UTC

**Comment by eibrahim** [comment] 2016-02-18 21:34
I am getting the broken @import errors with the ember-cli-jquery-ui addon...  The only way I was able to make my build work was to add 
```
    minifyCSS: {
      enabled: false,
    },
```

But obviously this turns off my CSS minification...  Any idea what is going on?

The full error is:
```
File: assets/vendor.css
Broken @import declaration of "theme.css"
Broken @import declaration of "accordion.css"
Broken @import declaration of "autocomplete.css"
Broken @import declaration of "button.css"
Broken @import declaration of "datepicker.css"
Broken @import declaration of "dialog.css"
Broken @import declaration of "draggable.css"
Broken @import declaration of "menu.css"
Broken @import declaration of "progressbar.css"
Broken @import declaration of "resizable.css"
Broken @import declaration of "selectable.css"
Broken @import declaration of "selectmenu.css"
Broken @import declaration of "sortable.css"
Broken @import declaration of "slider.css"
Broken @import declaration of "spinner.css"
Broken @import declaration of "tabs.css"
Broken @import declaration of "tooltip.css"
Error: Broken @import declaration of "theme.css"
Broken @import declaration of "accordion.css"
Broken @import declaration of "autocomplete.css"
Broken @import declaration of "button.css"
Broken @import declaration of "datepicker.css"
Broken @import declaration of "dialog.css"
Broken @import declaration of "draggable.css"
Broken @import declaration of "menu.css"
Broken @import declaration of "progressbar.css"
Broken @import declaration of "resizable.css"
Broken @import declaration of "selectable.css"
Broken @import declaration of "selectmenu.css"
Broken @import declaration of "sortable.css"
Broken @import declaration of "slider.css"
Broken @import declaration of "spinner.css"
Broken @import declaration of "tabs.css"
Broken @import declaration of "tooltip.css"
    at arrayToError (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/array-to-error/index.js:41:15)
    at minifyCallback (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css-promise/index.js:33:20)
    at whenSourceMapReady (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/clean.js:139:16)
    at Object.whenDone (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/clean.js:155:14)
    at processNext (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at inlineLocalResource (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:347:12)
    at inline (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:218:10)
    at importFrom (/Users/admin/src/novetta/master/waremanpro/nea-client/node_modules/clean-css/lib/imports/inliner.js:74:12)
```

**Comment by eibrahim** [comment] 2016-02-18 21:49
by the way `ember build` works but `ember build --environment production` breaks which I guess comes back to minifyCSS.enabled = true

**Comment by stefanpenner** [comment] 2016-02-18 22:19
@eibrahim let me recommend you open a new issue, and link back to this one.
